### ISSUE TITLE
0.3.5

### ISSUE THREAD

**Issue by XianTong-king** [D-Sketon/hexo-theme-reimu#58]
![image](https://github.com/user-attachments/assets/0326854c-dbbd-430f-8809-bef0810daa04)
你好我更新了版本就变成这样了，是操作不对吗

**Comment by D-Sketon** [comment]
1. 你是从哪个版本升级到0.3.5
2. 请提供hexo控制台报错日志供排查

**Comment by XianTong-king** [comment]
ERROR Asset render failed: css/loader.css
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Hexo.<anonymous> (E:\web\github\xiantong'blog\themes\reimu\scripts\filter
\stylus.js:35:29)
    at Filter.execSync (E:\web\github\xiantong'blog\node_modules\hexo\dist\exten
d\filter.js:72:36)
    at Hexo.execFilterSync (E:\web\github\xiantong'blog\node_modules\hexo\dist\h
exo\index.js:403:35)
    at Renderer.<anonymous> (E:\web\github\xiantong'blog\node_modules\hexo-rende
rer-stylus\lib\renderer.js:57:24)
    at Renderer.use (E:\web\github\xiantong'blog\node_modules\stylus\lib\rendere
r.js:188:8)
    at Hexo.stylusFn (E:\web\github\xiantong'blog\node_modules\hexo-renderer-sty
lus\lib\renderer.js:57:6)
    at Hexo.promisified (E:\web\github\xiantong'blog\node_modules\bluebird\js\re
lease\promisify.js:223:16)
    at E:\web\github\xiantong'blog\node_modules\hexo\dist\hexo\render.js:73:28
    at tryCatcher (E:\web\github\xiantong'blog\node_modules\bluebird\js\release\
util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\web\github\xiantong'blog\node_modul
es\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\web\github\xiantong'blog\node_modules\bluebird
\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\web\github\xiantong'blog\node_modules\bluebir
d\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\web\github\xiantong'blog\node_modules\bluebir
d\js\release\promise.js:729:18)
lus\lib\renderer.js:57:6)
    at Hexo.promisified (E:\web\github\xiantong'blog\node_modules\bluebird\js\release\promisify.js:223:16)
    at E:\web\github\xiantong'blog\node_modules\hexo\dist\hexo\render.js:73:28
    at tryCatcher (E:\web\github\xiantong'blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\web\github\xiantong'blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\web\github\xiantong'blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\web\github\xiantong'blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\web\github\xiantong'blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\web\github\xiantong'blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\web\github\xiantong'blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\web\github\xiantong'blog\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (E:\web\github\xiantong'blog\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:491:21)



0.3.4

**Comment by XianTong-king** [comment]
> 1. 你是从哪个版本升级到0.3.5
> 2. 请提供hexo控制台报错日志供排查

昨天安装的0.3.4正常
文章都在首页里面了，背景图占满屏幕

**Comment by D-Sketon** [comment]
你是通过git clone的方式下载的主题吗，如果是的话再拉取一下，刚才https://github.com/D-Sketon/hexo-theme-reimu/commit/ac0f7b5d68f9374b2c065c7021ec1490af1420f4 应该修复了

**Comment by XianTong-king** [comment]
> 你是通过git clone的方式下载的主题吗，如果是的话再拉取一下，刚才[ac0f7b5](https://github.com/D-Sketon/hexo-theme-reimu/commit/ac0f7b5d68f9374b2c065c7021ec1490af1420f4) 应该修复了

可以了谢谢
