### ISSUE TITLE
替换主题后报错

### ISSUE THREAD

**Issue by zhaozhuohua** [D-Sketon/hexo-theme-reimu#73]
替换主题后报错
执行
hexo clean
hexo g
hexo d
都会报错

```
ERROR Script load failed: themes\reimu\scripts\filter\stylus.js
D:\work\html\blog\blog-hexo\themes\reimu\scripts\filter\stylus.js:3
  const articleFamilies = (hexo.theme.config.font?.article ?? [])
                                                  ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at runInThisContext (vm.js:309:10)
    at D:\work\html\blog\blog-hexo\node_modules\hexo\dist\hexo\index.js:254:50
    at tryCatcher (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
ERROR Script load failed: themes\reimu\scripts\helper\articleCopyright.js
D:\work\html\blog\blog-hexo\themes\reimu\scripts\helper\articleCopyright.js:5
  const dateDom = `<p><strong>本文发布时间：</strong>${post.date?.format(
                                                          ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at runInThisContext (vm.js:309:10)
    at D:\work\html\blog\blog-hexo\node_modules\hexo\dist\hexo\index.js:254:50
    at tryCatcher (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
ERROR Script load failed: themes\reimu\scripts\helper\config.js
D:\work\html\blog\blog-hexo\themes\reimu\scripts\helper\config.js:19
  if (config.service_worker?.enable) {
                            ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at runInThisContext (vm.js:309:10)
    at D:\work\html\blog\blog-hexo\node_modules\hexo\dist\hexo\index.js:254:50
    at tryCatcher (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
ERROR Script load failed: themes\reimu\scripts\helper\outdate.js
D:\work\html\blog\blog-hexo\themes\reimu\scripts\helper\outdate.js:3
  if (config.outdate?.enable) {
                     ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at runInThisContext (vm.js:309:10)
    at D:\work\html\blog\blog-hexo\node_modules\hexo\dist\hexo\index.js:254:50
    at tryCatcher (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
ERROR Script load failed: themes\reimu\scripts\helper\parseHomeCategories.js
D:\work\html\blog\blog-hexo\themes\reimu\scripts\helper\parseHomeCategories.js:12
    hexo.locals.get("categories").find({ name: category })?.first()?.length ||
                                                           ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at runInThisContext (vm.js:309:10)
    at D:\work\html\blog\blog-hexo\node_modules\hexo\dist\hexo\index.js:254:50
    at tryCatcher (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
ERROR Script load failed: themes\reimu\scripts\helper\vendorFont.js
D:\work\html\blog\blog-hexo\themes\reimu\scripts\helper\vendorFont.js:7
  const basicConfigFontFamilies = [...(hexo.theme.config.font?.article ?? []), ...(hexo.theme.config.font?.code ?? [])]
                                                              ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at runInThisContext (vm.js:309:10)
    at D:\work\html\blog\blog-hexo\node_modules\hexo\dist\hexo\index.js:254:50
    at tryCatcher (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
ERROR Script load failed: themes\reimu\scripts\tag\postLinkCard.js
D:\work\html\blog\blog-hexo\themes\reimu\scripts\tag\postLinkCard.js:32
      cover = last ?? "";
                    ^

SyntaxError: Unexpected token '?'
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at runInThisContext (vm.js:309:10)
    at D:\work\html\blog\blog-hexo\node_modules\hexo\dist\hexo\index.js:254:50
    at tryCatcher (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
ERROR Script load failed: themes\reimu\scripts\util\checkVersion.js
Error: Cannot find module 'node:https'
Require stack:
- D:\work\html\blog\blog-hexo\themes\reimu\scripts\util\checkVersion.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at req (D:\work\html\blog\blog-hexo\node_modules\hexo\dist\hexo\index.js:247:31)
    at D:\work\html\blog\blog-hexo\themes\reimu\scripts\util\checkVersion.js:1:86
    at D:\work\html\blog\blog-hexo\node_modules\hexo\dist\hexo\index.js:255:20
    at tryCatcher (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (D:\work\html\blog\blog-hexo\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by D-Sketon** [comment]
需要node版本大于等于16

**Comment by zhaozhuohua** [comment]
升级node后确实好了
谢谢
